name: Docker

on:
  push:
    branches:
      - dev

jobs:
  build-x86:
    runs-on: ubuntu-latest
    environment: DOCKERHUB

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (x86)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.d/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urlapi:latest

  build-arm64:
    runs-on: ubuntu-24.04-arm
    environment: DOCKERHUB

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.d/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urlapi-arm:latest
